### PR TITLE
Initiating Nautobot jobs

### PR DESCRIPTION
**Pull request by MeganerdDev**
# Closes: #223

## What's Changed

- Adds `init_job` subccomand which initiates a Nautobot job by job name

## Remaining work
- The acceptance criteria of this PR would require mapping of the username of the user interacting with the chatbot to the username of the user in Nautobot
- The render markdown is incomplete, the present output is a placeholder
- Add supporting subcommand: `get_jobs`
- Add to documentation

## TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/chatops/en/latest/dev/contributing/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [x] Outline Remaining Work, Constraints from Design

## Notes
- Tested to be working from ChatOps+Mattermost but must statically set the user the job runs as
- Adding a parameter for the user is possible but seems non-preferred solution
- We could also initiate jobs from API, but the ORM makes more sense?

### CODE REVIEW

**Comment by MeganerdDev** [comment]
Also, I used `init_job` since the `run_job` namespace is already being used by core, and changing the `import run_job as something_else` seemed like bad practice.

**Comment by MeganerdDev** [comment]
@smk4664 @jvanderaa

**Comment by MeganerdDev** [comment]
I moved the base for the merge to `next-2.0`

**Comment by MeganerdDev** [comment]
I need to test this to confirm working as expected! I followed the pattern I believed was proper however.


I am blocked by an issue getting my homelab up for testing this. Does this look like user error for my homelab?
I am on `Chatops next-2.0 branch (3.0.0rc1)`  with `Nautobot v2.0.0rc3`
To rule out nautobot as the issue I ran migrate, post_upgrade, collectstatic
image

**Comment by smk4664** [comment]
> I need to test this to confirm working as expected! I followed the pattern I believed was proper however.
> 
> I am blocked by an issue getting my homelab up for testing this. Does this look like user error for my homelab? I am on `Chatops next-2.0 branch (3.0.0rc1)` with `Nautobot v2.0.0rc3` To rule out nautobot as the issue I ran migrate, post_upgrade, collectstatic image

I thought I fixed this, but I am not seeing the fix applied. I will push the changes so you can test.

**Comment by MeganerdDev** [comment]
Hi @smk4664, I updated and tested this feature on #270  to be working (outside of some noted edge cases)

I was having some GIT troubles rebasing this to next-2.0 properly and didn't have the time to fit GIT. Hope that is okay! I modified the fragment and all.

**Comment by MeganerdDev** [comment]
closed in favor of #270

**Pull request closed without merging**
