### PR TITLE
Add Arista CloudVision integration

### PR DESCRIPTION
**Pull request by snaselj**
# Closes: #204 

## What's Changed

- Added Arista CloudVision integration from nautobot-plugin-chatops-arista-cloudvision.

## TODO

- [ ] Test the integration.

### CODE REVIEW

**Comment by snaselj** [comment]
Rebased on top of develop.

**Comment by snaselj** [comment]
This PR is ready for review now.

**Review by smk4664 — APPROVED** [review]
These changes look great! I am unable to test though as there is an issue with our CloudVision instance. Once this issue is resolved, I will test and merge.

**Comment by snaselj** [comment]
Conflicts resolved by merging with the latest `develop`.

**Comment by snaselj** [comment]
Conflicts resolved by merging with the latest `develop`.

**Pull request merged**
