### PR TITLE
Updates for minor release 1.7

### PR DESCRIPTION
**Pull request by jvanderaa**
Release 1.7 with the new features of the CSV Export and autofocus. Bug fixes.

### CODE REVIEW

**Comment by jvanderaa** [comment]
@glennmatthews @smk4664 any issues?

**Comment by david-kn** [comment]
Hi, any chance for some progress?

**Comment by susanhooks** [comment]
@glennmatthews Could we possibly get this merged? It's some documentation update/bump version to go along with work @jvanderaa did on the chat bot.

**Comment by smk4664** [comment]
@david-kn @jvanderaa @susanhooks I will be reviewing this today.

**Review by smk4664 — APPROVED** [review]
LGTM

**Pull request merged**
